USE [DBInspetorCMS]
GO
CREATE TABLE REGRASXML (
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRICAO VARCHAR(500) NULL,
CONTEUDO VARCHAR(300) NULL,
TIPO CHAR(1) NULL,
ORDEM TINYINT NULL,
ATIVO BIT NULL,
TIPO_VALIDACAO VARCHAR(100) NULL,
PROCESSO VARCHAR(100) NULL
);